name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        rust: [
          beta,
          nightly,
          1.79.0,
          # stable, # uncomment this once github uses 1.79.0 for stable
        ]

    steps:
    - uses: actions/checkout@v3
    - name: stuff
      run: |
        set -ex
        rustup override set ${{ matrix.rust }}
        cargo build --verbose
        cargo test --verbose

    - uses: actions/checkout@v3
    - name: ui-test
      if: ${{ matrix.rust == 'nightly' }}
      run: |
        set -ex
        rustup override set ${{ matrix.rust }}
        cargo test --features __ui_tests --verbose
