name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        rust: [nightly]

    steps:
    - uses: actions/checkout@v3
    - name: stuff
      run: |
        set -ex
        rustup override set ${{ matrix.rust }}
        cargo build --verbose
        cargo test --verbose
